# Generated by Django 5.0.6 on 2024-06-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('pdes', models.CharField(max_length=100)),
                ('pprice', models.IntegerField()),
                ('piamge', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'addproduct',
            },
        ),
    ]
