# Generated by Django 5.0.6 on 2024-06-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_addpro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addpro',
        ),
    ]
