# Generated by Django 5.0.6 on 2024-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_delete_addpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('pdesc', models.CharField(max_length=100)),
                ('prices', models.IntegerField()),
                ('pcategory', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'addcategory',
            },
        ),
    ]
