# Generated by Django 5.0.6 on 2024-06-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_delete_addpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('pdesc', models.CharField(max_length=100)),
                ('prices', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('pcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.category')),
            ],
            options={
                'db_table': 'addproduct',
            },
        ),
    ]
