# Generated by Django 5.0.6 on 2024-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_alter_addpro_pdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpro',
            name='image',
            field=models.URLField(),
        ),
    ]
