# Generated by Django 5.0.6 on 2024-06-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_alter_addpro_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoryname',
        ),
    ]
