# Generated by Django 5.0.6 on 2024-06-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_rename_category_category_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpro',
            old_name='pdesc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='addpro',
            old_name='prices',
            new_name='price',
        ),
    ]
