# Generated by Django 5.0.6 on 2024-06-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_rename_pdesc_addpro_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addpro',
            new_name='Product',
        ),
    ]
