# Generated by Django 5.0.6 on 2024-07-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_remove_banner_bannerimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
