# Generated by Django 5.0.6 on 2024-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=50)),
                ('manageremail', models.CharField(max_length=50)),
                ('managerpassword', models.CharField(default='Manager@123', max_length=50)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
