# Generated by Django 5.0.6 on 2024-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='managerpassword',
            field=models.CharField(max_length=200),
        ),
    ]
