# Generated by Django 5.0.6 on 2024-07-13 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0016_alter_manager_managerpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 13, 15, 37, 48, 183969)),
        ),
    ]
