# Generated by Django 5.0.6 on 2024-07-14 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0025_alter_manager_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 14, 8, 20, 32, 108610, tzinfo=datetime.timezone.utc)),
        ),
    ]
