# Generated by Django 5.0.6 on 2024-07-23 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0027_alter_manager_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 9, 26, 48, 799293, tzinfo=datetime.timezone.utc)),
        ),
    ]
