# Generated by Django 5.0.6 on 2024-07-23 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0028_alter_manager_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 10, 37, 23, 813076, tzinfo=datetime.timezone.utc)),
        ),
    ]
