# Generated by Django 5.0.6 on 2024-07-23 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0030_alter_manager_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 11, 16, 17, 750690, tzinfo=datetime.timezone.utc)),
        ),
    ]
