# Generated by Django 5.0.6 on 2024-09-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0037_alter_manager_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 21, 40, 37, 330670)),
        ),
    ]
