# Generated by Django 5.0.6 on 2024-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantapp', '0002_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('uid', models.IntegerField(max_length=5)),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
    ]
