# Generated by Django 5.0.6 on 2024-06-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_booktable_alter_udetails_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booktable',
        ),
    ]
