# Generated by Django 5.0.6 on 2024-06-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_rename_addpro_product'),
        ('restaurantapp', '0010_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_itmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.product')),
            ],
            options={
                'db_table': 'cartitemss',
            },
        ),
    ]
