# Generated by Django 5.0.6 on 2024-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0011_cart_itmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_itmes',
            name='itemPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart_itmes',
            name='itemTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart_itmes',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
