# Generated by Django 5.0.6 on 2024-07-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0028_alter_manager_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitercart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pquantity', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.product')),
            ],
            options={
                'db_table': 'waitercart',
            },
        ),
    ]
