# Generated by Django 5.0.6 on 2024-07-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_chef_last_login_alter_tables_tableno_and_more'),
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitercart',
            name='tableno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.tables'),
        ),
    ]
