# Generated by Django 5.0.6 on 2024-07-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_chef_last_login_alter_waiter_last_login'),
        ('waiter', '0002_waitercart_tableno'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitercart',
            name='wid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.waiter'),
        ),
    ]
