# Generated by Django 5.0.6 on 2024-07-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
