# Generated by Django 5.0.6 on 2024-07-24 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_chef_last_login_alter_waiter_last_login'),
        ('waiter', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('pquantity', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('tableno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.tables')),
                ('wid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.waiter')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
