# Generated by Django 5.0.6 on 2024-07-14 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefname', models.CharField(max_length=50)),
                ('chefemail', models.CharField(max_length=50)),
                ('chefpassword', models.CharField(max_length=200)),
                ('last_login', models.DateField(default=datetime.datetime(2024, 7, 14, 8, 20, 32, 113064, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'chef',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitername', models.CharField(max_length=50)),
                ('waiteremail', models.CharField(max_length=50)),
                ('waiterpassword', models.CharField(max_length=200)),
                ('last_login', models.DateField(default=datetime.datetime(2024, 7, 14, 8, 20, 32, 113064, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'waiter',
            },
        ),
    ]
