# Generated by Django 5.0.6 on 2024-07-22 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNo', models.IntegerField()),
                ('tableSize', models.IntegerField()),
            ],
            options={
                'db_table': 'tables',
            },
        ),
        migrations.AlterField(
            model_name='chef',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 12, 4, 24, 7530, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 12, 4, 24, 6557, tzinfo=datetime.timezone.utc)),
        ),
    ]
