# Generated by Django 5.0.6 on 2024-07-23 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_chef_last_login_alter_waiter_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 10, 37, 23, 816043, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tables',
            name='tableNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 10, 37, 23, 816043, tzinfo=datetime.timezone.utc)),
        ),
    ]
