# Generated by Django 5.0.6 on 2024-07-26 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_chef_last_login_alter_waiter_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chef',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 8, 36, 17, 446145, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 6, 17, 446145)),
        ),
    ]
