# Generated by Django 5.0.6 on 2024-09-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_waiter_is_authenticated_alter_chef_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='isActive',
            field=models.CharField(default='close', max_length=20),
        ),
        migrations.AlterField(
            model_name='chef',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 16, 10, 37, 334083, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 21, 40, 37, 334083)),
        ),
    ]
