# Generated by Django 5.0.6 on 2024-09-13 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_tables_isactive_alter_chef_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 9, 13, 9, 48, 26, 655100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 9, 13, 15, 18, 26, 655100)),
        ),
    ]
